version: '3'
services:
  api:
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    ports:
      - '3333:3333'
    restart: always
  client:
    build:
      context: .
      dockerfile: ./apps/perf-analytics/Dockerfile
    ports:
      - '80:80'
    restart: always
